apiVersion: v1
kind: Service
metadata:
  name: servicio-andres-zapata
  namespace: namespace-andres-zapata
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80